# Generated by Django 4.2.18 on 2025-07-12 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customnote", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("base_menu", models.CharField(max_length=100)),
                ("temperature", models.CharField(blank=True, max_length=20)),
                ("option", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
