# Generated by Django 4.2.18 on 2025-07-17 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customnote", "0002_custommenu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccessToken",
        ),
    ]
